### ISSUE TITLE
Still Get .txt files, using Goeswin.conf

### ISSUE THREAD

**Issue by rtromeo** [creinemann/EMWIN-NON-CMIP-SCRIPTS-FOR-GOESTOOLS#1]
First Off, BIG THANK you for the Work and CONF files, they work great and offer a lot more Images and Info.

I am using this:

[[handler]]
type = "emwin"
directory = "./emwin/{time:%Y-%m-%d}"
exclude_txt = true

But still getting hundreds of TEXT files........ any Ideas on how to fix that ?

Thanks again for your time !

**Comment by creinemann** [comment]
Did you make the changes outlined in 
https://github.com/tmbates12/goestools/commit/2f54169cabfe05c6bfdc4f68dca0307fe7117df1  

Once that is done you need to recompile goest tools.
Have a look at my page here and scroll down to-
**_How to get rid of EMWIN text_**

**Comment by rtromeo** [comment]
Carl;

Thank you very much, i missed the part on your site that explains how to modify the code and recompile. I have read it, and done that , and it is working like a charm!
No longer getting the .txt files just the images.

Thank you again for the work you have done, this is such a cool project.. I for one really appreciate it!

Cheers

Ross Romeo
